name: gita
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.3+4

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # flutter_screenutil: ^5.5.3+1
  flutter_svg: ^1.0.3
  # google_fonts: ^2.3.2  
  easy_localization: ^3.0.0
  easy_localization_loader: ^1.0.0
  # dio: ^4.0.6
  dio:
  flutter_secure_storage: ^5.0.2
  path_provider: ^2.0.10
  # auto_route: ^4.0.1
  intl: ^0.17.0
  flutter_bloc: ^8.0.1
  hydrated_bloc: ^8.1.0
  connectivity_plus: ^2.3.0
  flutter_local_notifications: ^13.0.0
  rxdart: ^0.27.4
  cached_network_image: ^3.2.0
  freezed_annotation: ^2.2.0
  equatable: ^2.0.5
  image_picker:
  image_cropper: ^3.0.1
  floating_bottom_navigation_bar: ^1.5.2
  share_plus: ^6.3.0
  screenshot: ^1.3.0
  flutter_carousel_widget: ^1.2.2
  # google_mobile_ads: ^2.3.0
  firebase_core: ^2.4.1
  # awesome_dialog: ^3.0.2
  # chewie: ^1.4.0
  url_launcher: ^6.1.8
  # new_version: ^0.3.0
  # video_player: ^2.5.1
  # facebook_audience_network: ^1.0.1
  firebase_messaging: ^14.2.1
  shimmer: ^2.0.0
  lottie: ^2.2.0
  # firebase_analytics: ^10.1.0/
  # upgrader: ^6.0.1
  # upgrader:
  # animation_wrappers: ^3.0.0
  # widget_mask: ^1.0.0+0
  flutter_windowmanager: ^0.2.0
  # gesture_detector_x: ^1.0.0
  google_fonts: ^3.0.1
  stroke_text: ^0.0.2
  flutter_colorpicker: ^1.0.3
  flutter_form_builder:
  # screenshot_callback:

  # ----------------Video player packages------------------------------
  
  card_swiper: ^2.0.4
  # video_player: ^2.6.1
  # video_editor:

  flutter_cache_manager: ^3.3.1

  in_app_update: ^4.2.2

  qr_flutter: ^4.0.0

  smart_snackbars: ^1.0.0
  overlay_support: ^2.1.0
  # skeletonizer:
  skeletons: ^0.0.3
  logger: ^2.0.2+1

  bubble_box: ^0.5.3
  flutter_rating_bar: ^4.0.1
  youtube_player_flutter: ^8.1.2
  android_play_install_referrer: ^0.3.0
  youtube_player_iframe: ^4.0.4
  gif:

  # sms_autofill: ^2.3.0
  flutter_tts: ^4.0.2
  permission_handler: ^10.2.0
  package_info_plus:
  font_awesome_flutter: ^10.4.0
  crypto: ^3.0.2
  gallery_saver: ^2.3.2
  camera:
  razorpay_flutter:
  zwidget: ^0.0.2
  interactive_box:
  # camerawesome:
  neon_widgets:
  # haptic_feedback:
  # auto_size_text_field:
  # appflowy_editor:
  # flutter_quill:
  flutter_chat_bubble: ^2.0.2
  any_link_preview: ^3.0.0
  flutter_contacts:
  fl_chart:
  # qr_code_scanner: ^1.0.1
  # qr_flutter: ^3.2.0
  # barcode_scan_fix:
  awesome_notifications:
  objectbox: ^4.0.2
  objectbox_flutter_libs:
  just_audio:
  ffmpeg_kit_flutter_min_gpl:
  video_player: 
  flutter_ffmpeg:


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  build_runner: ^2.0.0
  objectbox_generator:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translation/
    - assets/images/
    # - assets/test/
    - assets/frames/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
